Repository CosMos-Organization/cosmos-groupware, pull requests merged in 2024-03, with the labels that each got.

#14 Feature/setting swagger
  Back-end/cosmos/build.gradle
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/config/SwaggerConfig.java
  Back-end/cosmos/src/main/resources/application.yml
Labels: setting

#20 #19 application.yml 환경분리 (local, dev)
  Back-end/cosmos/src/main/resources/application-dev.yml
  Back-end/cosmos/src/main/resources/application-local.yml
  Back-end/cosmos/src/main/resources/application.yml
Labels: setting

#36 Feature/spring security setting
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/config/SecurityConfig.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/member/entity/Member.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/member/repository/MemberRepository.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/member/service/CustomUserDetailService.java
Labels: setting

#39 feat : git log aspect 설정 추가
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/global/aspect/LogIntroduction.java
  Back-end/cosmos/src/main/resources/application.yml
Labels: setting

#40 #26 QueryDsl 설정
  Back-end/cosmos/.gitignore
  Back-end/cosmos/build.gradle
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/config/QueryDslConfig.java
Labels: setting

#49 RestControllerAdvice 및 custom Exception추가
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/global/advice/ErrorResponse.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/global/advice/GlobalErrorAdvice.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/global/exception/NotFoundResultException.java
Labels: setting, feature

#64 어드민_사원관리 수정
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/config/SecurityConfig.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/member/controller/MemberController.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/member/dto/MemberDTO.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/member/dto/request/MemberRequest.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/member/dto/response/MemberResponse.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/member/entity/Member.java
  Back-end/cosmos/src/main/java/com/nklcb/cosmos/member/service/MemberService.java
Labels: feature
